name: win64_vs2019

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.2.0
      
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Make 3rdParty and project
      run: ${{github.workspace}}/make_win64_vs2019.bat

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build Debugx64
      run: msbuild ${{github.workspace}}/AssetPipeline.sln /p:Configuration=Debug /p:Platform=x64
      
    - name: Build Releasex64
      run: msbuild ${{github.workspace}}/AssetPipeline.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload built results to Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: cdscene_sdk_win64_vs2019
        path: |
          ${{github.workspace}}/public/**/*.*
          ${{github.workspace}}/build/bin/**/AssetPipelineCore.*
          ${{github.workspace}}/build/bin/**/CDConsumer.*
          ${{github.workspace}}/build/bin/**/CDProducer.*
          ${{github.workspace}}/build/bin/**/GenericProducer.*
          ${{github.workspace}}/build/bin/**/assimp-vc142-mtd.*
          ${{github.workspace}}/build/bin/**/GenericToORMToCD.*
