name: win64_vs2022

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Make 3rdParty and project
      run: ${{github.workspace}}/make_win64_vs2022.bat

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build Debugx64
      run: msbuild ${{github.workspace}}/AssetPipeline.sln /p:Configuration=Debug /p:Platform=x64
      
    - name: Build Releasex64
      run: msbuild ${{github.workspace}}/AssetPipeline.sln /p:Configuration=Release /p:Platform=x64
